import { useEffect, useRef, useState, useSyncExternalStore } from "react";
import { AssistantRuntimeProvider } from "@assistant-ui/react";
import * as apiClient from "./api";
import { useLibreNmsExternalStoreRuntime } from "./runtime";
import { AssistantChatStore } from "./store";
import { readPluginIdentity } from "./identity";
import { ChatTranscript } from "./components/ChatTranscript";
import { Composer } from "./components/Composer";
import { DeleteThreadDialog } from "./components/DeleteThreadDialog";
import { RunMetrics } from "./components/RunMetrics";
import { RunProgress } from "./components/RunProgress";
import { ThreadDrawer } from "./components/ThreadDrawer";
import { ThreadList } from "./components/ThreadList";
import styles from "./App.module.css";

const defaultStore = new AssistantChatStore();
const defaultIdentity = readPluginIdentity();
const clientMessageId = () => globalThis.crypto?.randomUUID?.() || `message-${Date.now()}`;
export default function App({ chatStore = defaultStore, identity = defaultIdentity, api = apiClient }) {
  const state = useSyncExternalStore(chatStore.subscribe, chatStore.getSnapshot, chatStore.getSnapshot);
  const [deleteTarget, setDeleteTarget] = useState(null); const [sessionExpired, setSessionExpired] = useState(false);
  const activeRunsRef = useRef(new Map()); const deleteTriggerRef = useRef(null); const mainRef = useRef(null); const token = identity?.token || "";
  const expireSession = (threadId, messageId) => { if (messageId) chatStore.dispatch({ type: "message.discard", threadId, clientMessageId: messageId }); setSessionExpired(true); };
  const refreshThread = async (threadId) => { try { const thread = await api.getThread(threadId, token); if (chatStore.getSnapshot().threads.some((item) => item.id === threadId)) chatStore.dispatch({ type: "thread.loaded", preserveSelection: true, thread }); } catch (error) { if (error.status === 401) expireSession(); } };
  useEffect(() => { if (!token) return; api.listThreads(token).then((threads) => chatStore.dispatch({ type: "threads.loaded", threads })).catch((error) => { if (error.status === 401) expireSession(); }); }, [api, chatStore, token]);
  const select = async (threadId) => { try { const thread = await api.getThread(threadId, token); if (chatStore.getSnapshot().threads.some((item) => item.id === threadId)) chatStore.dispatch({ type: "thread.loaded", thread }); } catch (error) { if (error.status === 401) expireSession(); } };
  const create = async () => { try { const thread = await api.createThread(token); chatStore.dispatch({ type: "thread.created", thread }); } catch (error) { if (error.status === 401) expireSession(); } };
  const terminalFailure = (threadId, messageId, error) => { const runId = chatStore.getSnapshot().runs[threadId]?.id; if (runId) { chatStore.dispatch({ type: "stream.event", threadId, clientMessageId: messageId, event: "error", data: { run_id: runId, ...error } }); chatStore.dispatch({ type: "stream.event", threadId, clientMessageId: messageId, event: "completed", data: { run_id: runId, status: "failed", used_fallback: false, metrics: null } }); } else chatStore.dispatch({ type: "run.failed", threadId, error }); };
  const send = async (content) => { let threadId = chatStore.getSnapshot().selectedThreadId; if (sessionExpired || !token) return; if (!threadId) { try { const thread = await api.createThread(token); chatStore.dispatch({ type: "thread.created", thread }); threadId = thread.id; } catch (error) { if (error.status === 401) expireSession(); return; } } const id = clientMessageId(); const controller = new AbortController(); chatStore.dispatch({ type: "message.optimistic", threadId, clientMessageId: id, content }); const onEvent = (event, data) => { chatStore.dispatch({ type: "stream.event", threadId, clientMessageId: id, event, data }); if (event === "completed") refreshThread(threadId); }; const promise = api.runThread(threadId, id, content, token, controller.signal, onEvent); const active = { controller, promise }; activeRunsRef.current.set(threadId, active); try { await promise; } catch (error) { if (error.name === "AbortError") { const runId = chatStore.getSnapshot().runs[threadId]?.id; if (runId) chatStore.dispatch({ type: "stream.event", threadId, clientMessageId: id, event: "completed", data: { run_id: runId, status: "cancelled", used_fallback: false, metrics: null } }); } else if (error.status === 401) expireSession(threadId, id); else if (error.status === 409) { chatStore.dispatch({ type: "message.discard", threadId, clientMessageId: id }); terminalFailure(threadId, id, { stage: "transport", code: "run_conflict", retryable: false, message: "This investigation already has a run." }); } else terminalFailure(threadId, id, { stage: "transport", code: "transport_failed", retryable: true, message: "The connection ended before the investigation completed." }); } finally { if (activeRunsRef.current.get(threadId) === active) activeRunsRef.current.delete(threadId); } };
  const closeDelete = () => { setDeleteTarget(null); requestAnimationFrame(() => deleteTriggerRef.current?.focus()); };
  const confirmDelete = async () => { const target = deleteTarget; if (!target) return; const active = activeRunsRef.current.get(target.id); if (active) { active.controller.abort(); await active.promise.catch(() => {}); } try { await api.deleteThread(target.id, token); chatStore.dispatch({ type: "thread.deleted", threadId: target.id }); setDeleteTarget(null); requestAnimationFrame(() => mainRef.current?.focus()); } catch (error) { if (error.status === 401) expireSession(); } };
  const selectedMessages = state.selectedThreadId ? state.messages[state.selectedThreadId] || [] : []; const run = state.selectedThreadId ? state.runs[state.selectedThreadId] : null; const runtime = useLibreNmsExternalStoreRuntime(chatStore, state.selectedThreadId, send, () => activeRunsRef.current.get(state.selectedThreadId)?.controller.abort());
  return <AssistantRuntimeProvider runtime={runtime}><div className={styles.shell}><a className={styles.skip} href="#investigation-main">Skip saved investigations</a><ThreadDrawer open={state.drawerOpen} onClose={() => chatStore.dispatch({ type: "drawer.close" })} onCreate={create}><ThreadList threads={state.threads} selectedThreadId={state.selectedThreadId} onSelect={select} onDelete={(thread, trigger) => { deleteTriggerRef.current = trigger; setDeleteTarget(thread); }} /></ThreadDrawer><main ref={mainRef} tabIndex="-1" id="investigation-main" className={styles.main}><header className={styles.header}><button type="button" className={styles.menu} onClick={() => chatStore.dispatch({ type: "drawer.open" })} aria-label="Open investigations">☰</button><div><p>Read-only network investigation</p><h1>{state.threads.find((thread) => thread.id === state.selectedThreadId)?.title || "Start an investigation"}</h1></div></header>{sessionExpired ? <p className={styles.error} role="alert">Your LibreNMS session has expired. Refresh the page to continue.</p> : run?.error && <p className={styles.error} role="alert">{run.error.message}</p>}<RunProgress run={run} /><ChatTranscript messages={selectedMessages} /><RunMetrics metrics={run?.metrics} /><Composer disabled={!token || sessionExpired} running={run?.status === "running"} canRetry={!sessionExpired && run?.canRetry} onSend={send} onCancel={() => activeRunsRef.current.get(state.selectedThreadId)?.controller.abort()} onRetry={() => { const last = [...selectedMessages].reverse().find((message) => message.role === "user"); if (last) send(last.content); }} /></main><DeleteThreadDialog open={Boolean(deleteTarget)} threadTitle={deleteTarget?.title} onCancel={closeDelete} onConfirm={confirmDelete} /></div></AssistantRuntimeProvider>;
}
